# 💻 [Univariate - single step LSTM](https://youtu.be/LkoSAbKG_H8)
### 📚 [AI with Dr. Mo](https://www.youtube.com/c/AIwithDrMo/playlists)

In [1]:
import pandas as pd
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [2]:
df = pd.DataFrame({'x':list(range(17, 329))})
df

x
0     17
1     18
2     19
3     20
4     21
..   ...
307  324
308  325
309  326
310  327
311  328

[312 rows x 1 columns]

In [3]:
num_lags = 3

for i in range(num_lags+1):
    df.insert(loc=1, column=f't-{i}' , value=df.iloc[:,0].shift(periods=i))
print(df)

       x    t-3    t-2    t-1  t-0
0     17    NaN    NaN    NaN   17
1     18    NaN    NaN   17.0   18
2     19    NaN   17.0   18.0   19
3     20   17.0   18.0   19.0   20
4     21   18.0   19.0   20.0   21
..   ...    ...    ...    ...  ...
307  324  321.0  322.0  323.0  324
308  325  322.0  323.0  324.0  325
309  326  323.0  324.0  325.0  326
310  327  324.0  325.0  326.0  327
311  328  325.0  326.0  327.0  328

[312 rows x 5 columns]


In [4]:
df.dropna(inplace=True)

X = df.iloc[:,1:num_lags+1].values
y = df.iloc[:,num_lags+1:].values

print(X)
print(y)

[[ 17.  18.  19.]
 [ 18.  19.  20.]
 [ 19.  20.  21.]
 [ 20.  21.  22.]
 [ 21.  22.  23.]
 [ 22.  23.  24.]
 [ 23.  24.  25.]
 [ 24.  25.  26.]
 [ 25.  26.  27.]
 [ 26.  27.  28.]
 [ 27.  28.  29.]
 [ 28.  29.  30.]
 [ 29.  30.  31.]
 [ 30.  31.  32.]
 [ 31.  32.  33.]
 [ 32.  33.  34.]
 [ 33.  34.  35.]
 [ 34.  35.  36.]
 [ 35.  36.  37.]
 [ 36.  37.  38.]
 [ 37.  38.  39.]
 [ 38.  39.  40.]
 [ 39.  40.  41.]
 [ 40.  41.  42.]
 [ 41.  42.  43.]
 [ 42.  43.  44.]
 [ 43.  44.  45.]
 [ 44.  45.  46.]
 [ 45.  46.  47.]
 [ 46.  47.  48.]
 [ 47.  48.  49.]
 [ 48.  49.  50.]
 [ 49.  50.  51.]
 [ 50.  51.  52.]
 [ 51.  52.  53.]
 [ 52.  53.  54.]
 [ 53.  54.  55.]
 [ 54.  55.  56.]
 [ 55.  56.  57.]
 [ 56.  57.  58.]
 [ 57.  58.  59.]
 [ 58.  59.  60.]
 [ 59.  60.  61.]
 [ 60.  61.  62.]
 [ 61.  62.  63.]
 [ 62.  63.  64.]
 [ 63.  64.  65.]
 [ 64.  65.  66.]
 [ 65.  66.  67.]
 [ 66.  67.  68.]
 [ 67.  68.  69.]
 [ 68.  69.  70.]
 [ 69.  70.  71.]
 [ 70.  71.  72.]
 [ 71.  72.  73.]
 [ 72.  73

In [5]:
# reshape from [samples, num_lags] into [samples, num_lags, num_feat]
num_feat = 1
X = X.reshape((X.shape[0], X.shape[1], num_feat))

In [6]:
# define model
model = Sequential()
model.add(LSTM(40, activation='relu', input_shape=(num_lags, num_feat)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=200, verbose=0)

# get prediction
x_input = array([300, 301, 302])
x_input = x_input.reshape((1, num_lags, num_feat))
y_pred = model.predict(x_input, verbose=0)
print(y_pred)

2022-07-28 06:56:24.621647: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[302.99463]]
